sudo: false
os:
  - linux
language: node_js
before_script:
  - git clone --recursive https://github.com/armory3d/armorpaint
  - git clone https://github.com/armory3d/nodejs_bin armorpaint/nodejs_bin
  - armorpaint/nodejs_bin/copysysbin.sh
script: 
  - cd armorpaint
  - nodejs_bin/node Kha/make.js krom
