name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Kromx process
      run: node Kromx/make

    - name: extract v8_monolith
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: Kromx/v8/libraries/win32/release/v8_monolith.7z
        pathTarget: Kromx/v8/libraries/win32/release/

    - name: Kinc process
        run: node Kromx/Kinc/make -g direct3d11

    - name: build solution
      run: msbuild Kromx/build/Krom.sln /property:Configuration=Release
